# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QDialog

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(610, 100, 111, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 20, 441, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(140, 150, 81, 20))
        self.checkBox.setIconSize(QtCore.QSize(40, 40))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(140, 180, 81, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(410, 130, 104, 87))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuImagen = QtWidgets.QMenu(self.menubar)
        self.menuImagen.setObjectName("menuImagen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionCalcular = QtWidgets.QAction(MainWindow)
        self.actionCalcular.setObjectName("actionCalcular")
        self.actionMostrar = QtWidgets.QAction(MainWindow)
        self.actionMostrar.setObjectName("actionMostrar")
        self.actionCargar = QtWidgets.QAction(MainWindow)
        self.actionCargar.setObjectName("actionCargar")
        self.actionBorrar = QtWidgets.QAction(MainWindow)
        self.actionBorrar.setObjectName("actionBorrar")
        self.menuMenu.addAction(self.actionAbrir)
        self.menuMenu.addAction(self.actionCalcular)
        self.menuMenu.addAction(self.actionMostrar)
        self.menuImagen.addAction(self.actionCargar)
        self.menuImagen.addAction(self.actionBorrar)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuImagen.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.textEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Boton 1"))
        self.pushButton_2.setText(_translate("MainWindow", "Boton 2"))
        self.pushButton_3.setText(_translate("MainWindow", "Boton 3"))
        self.pushButton_4.setText(_translate("MainWindow", "Boton 4"))
        self.label.setText(_translate("MainWindow", "MI PRIMER PROGRAMA"))
        self.checkBox.setText(_translate("MainWindow", "opcion 1"))
        self.checkBox_2.setText(_translate("MainWindow", "opcion 2"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuImagen.setTitle(_translate("MainWindow", "Imagen"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionCalcular.setText(_translate("MainWindow", "Calcular"))
        self.actionMostrar.setText(_translate("MainWindow", "Mostrar"))
        self.actionCargar.setText(_translate("MainWindow", "Cargar"))
        self.actionBorrar.setText(_translate("MainWindow", "Borrar"))
